#!/usr/bin/env bash
# Reproduce task16 email triage RL training.

set -euo pipefail

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=1
fi

if [ -f "${HOME}/.pinchbench_env" ]; then
  set -a
  # shellcheck disable=SC1090
  source "${HOME}/.pinchbench_env"
  set +a
fi

if [ -n "${TASK16_MAX_PROMPT_LENGTH_OVERRIDE:-}" ]; then
  export MAX_PROMPT_LENGTH="${TASK16_MAX_PROMPT_LENGTH_OVERRIDE}"
elif [ -z "${MAX_PROMPT_LENGTH:-}" ] || [ "${MAX_PROMPT_LENGTH}" = "16000" ]; then
  export MAX_PROMPT_LENGTH=20000
fi
if [ -n "${TASK16_MAX_RESPONSE_LENGTH_OVERRIDE:-}" ]; then
  export MAX_RESPONSE_LENGTH="${TASK16_MAX_RESPONSE_LENGTH_OVERRIDE}"
elif [ -z "${MAX_RESPONSE_LENGTH:-}" ] || [ "${MAX_RESPONSE_LENGTH}" = "4096" ]; then
  export MAX_RESPONSE_LENGTH=12000
fi
if [ -n "${TASK16_TRAIN_LOG_PATH_OVERRIDE:-}" ]; then
  export TRAIN_LOG_PATH="${TASK16_TRAIN_LOG_PATH_OVERRIDE}"
fi
if [ -n "${TASK16_TOTAL_TRAINING_STEPS_OVERRIDE:-}" ]; then
  export TOTAL_TRAINING_STEPS="${TASK16_TOTAL_TRAINING_STEPS_OVERRIDE}"
fi
if [ -n "${TASK16_TEST_FREQ_OVERRIDE:-}" ]; then
  export TEST_FREQ="${TASK16_TEST_FREQ_OVERRIDE}"
fi
if [ -n "${TASK16_SAVE_FREQ_OVERRIDE:-}" ]; then
  export SAVE_FREQ="${TASK16_SAVE_FREQ_OVERRIDE}"
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TASK16_DATA_DIR="${TASK16_DATA_DIR:-${REPO_ROOT}/data/task16_prompts}"
TRAIN_LOG_PATH="${TRAIN_LOG_PATH:-${REPO_ROOT}/logs/task16_rl.log}"

mkdir -p "${TASK16_DATA_DIR}" "$(dirname "${TRAIN_LOG_PATH}")"

if [ "${REBUILD_TASK16_DATA:-0}" = "1" ] || [ ! -f "${TASK16_DATA_DIR}/train.parquet" ] || [ ! -f "${TASK16_DATA_DIR}/val.parquet" ]; then
  python3 "${REPO_ROOT}/scripts/build_task16_prompts.py" \
    --tasks-dir "${REPO_ROOT}/pinchbench_tasks" \
    --output-dir "${TASK16_DATA_DIR}"
fi

python3 "${REPO_ROOT}/scripts/check_data.py" "${TASK16_DATA_DIR}"

export VERL_MODEL="${VERL_MODEL:-Qwen/Qwen3-1.7B}"
export REWARD_MODE="${REWARD_MODE:-task16-event-only-v2}"
export PINCHBENCH_REWARD_MODULE_OVERRIDE="${PINCHBENCH_REWARD_MODULE_OVERRIDE:-${REPO_ROOT}/rewards/task16_event_reward.py}"
export DATA_DIR="${TASK16_DATA_DIR}"
export PINCHBENCH_DATA_DIR_OVERRIDE="${TASK16_DATA_DIR}"
export PINCHBENCH_TRAIN_FILE_OVERRIDE="${PINCHBENCH_TRAIN_FILE_OVERRIDE:-${TASK16_DATA_DIR}/train.parquet}"
export PINCHBENCH_VAL_FILE_OVERRIDE="${PINCHBENCH_VAL_FILE_OVERRIDE:-${TASK16_DATA_DIR}/val.parquet}"
export BATCH_SIZE="${BATCH_SIZE:-1}"
export VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-1}"
export MICRO_BATCH="${MICRO_BATCH:-1}"
export TOTAL_EPOCHS="${TOTAL_EPOCHS:-4}"
export TOTAL_TRAINING_STEPS="${TOTAL_TRAINING_STEPS:-32}"
export VAL_BEFORE_TRAIN="${VAL_BEFORE_TRAIN:-False}"
export TEST_FREQ="${TEST_FREQ:-4}"
export SAVE_FREQ="${SAVE_FREQ:-4}"
export PINCHBENCH_REWARD_RETURN_MODE="${PINCHBENCH_REWARD_RETURN_MODE:-turn}"
export PINCHBENCH_REWARD_ASSIGNMENT="${PINCHBENCH_REWARD_ASSIGNMENT:-turn_broadcast}"
export PINCHBENCH_NO_MASKED_WHITEN="${PINCHBENCH_NO_MASKED_WHITEN:-1}"
export PINCHBENCH_TASK16_TERMINAL_REWARD_WEIGHT="${PINCHBENCH_TASK16_TERMINAL_REWARD_WEIGHT:-0.8}"
export PINCHBENCH_TASK_EMA_INIT="${PINCHBENCH_TASK_EMA_INIT:-0.0}"
export PINCHBENCH_TASK_EMA_ALPHA="${PINCHBENCH_TASK_EMA_ALPHA:-0.05}"
export PINCHBENCH_TASK_EMA_VAR_INIT="${PINCHBENCH_TASK_EMA_VAR_INIT:-0.0}"
export ROLLOUT_TEMPERATURE="${ROLLOUT_TEMPERATURE:-0.8}"
export VAL_DO_SAMPLE="${VAL_DO_SAMPLE:-False}"
export VAL_TEMPERATURE="${VAL_TEMPERATURE:-1.0}"
export VAL_TOP_P="${VAL_TOP_P:-1.0}"
export VAL_TOP_K="${VAL_TOP_K:--1}"
export VAL_N="${VAL_N:-1}"
export MAX_TURNS="${MAX_TURNS:-8}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-20000}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-12000}"
export PINCHBENCH_TASK16_MAX_TOKENS_PER_TURN="${PINCHBENCH_TASK16_MAX_TOKENS_PER_TURN:-2048}"
export VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN:-32768}"
export VLLM_GPU_MEM_UTIL="${VLLM_GPU_MEM_UTIL:-0.22}"
export VLLM_MAX_NUM_SEQS="${VLLM_MAX_NUM_SEQS:-8}"
export ROLLOUT_LAYERED_SUMMON="${ROLLOUT_LAYERED_SUMMON:-False}"
export PINCHBENCH_AGENT_LOOP_RUNTIME="${PINCHBENCH_AGENT_LOOP_RUNTIME:-benchmark}"
export PINCHBENCH_OPENCLAW_CONTEXT_WINDOW="${PINCHBENCH_OPENCLAW_CONTEXT_WINDOW:-${VLLM_MAX_MODEL_LEN}}"
export PINCHBENCH_OPENCLAW_MAX_TOKENS="${PINCHBENCH_OPENCLAW_MAX_TOKENS:-8192}"
export PINCHBENCH_MODEL_TEMPERATURE="${PINCHBENCH_MODEL_TEMPERATURE:-0.7}"
export PINCHBENCH_MODEL_TOP_P="${PINCHBENCH_MODEL_TOP_P:-0.8}"
export PINCHBENCH_MODEL_TOP_K="${PINCHBENCH_MODEL_TOP_K:-20}"
export PINCHBENCH_BENCHMARK_MODEL_ID="${PINCHBENCH_BENCHMARK_MODEL_ID:-${VERL_MODEL##*/}}"
export OPENCLAW_MODEL_REASONING="${OPENCLAW_MODEL_REASONING:-0}"
export PINCHBENCH_RL_INJECT_TOOL_FORMAT_SUFFIX="${PINCHBENCH_RL_INJECT_TOOL_FORMAT_SUFFIX:-1}"
export RUN_VERSION="${RUN_VERSION:-task16_event_only_v2_qwen31}"
export PINCHBENCH_ROLLOUT_DIAGNOSTICS_PATH="${PINCHBENCH_ROLLOUT_DIAGNOSTICS_PATH:-${REPO_ROOT}/logs/${RUN_VERSION}_rollout_diagnostics.jsonl}"
export OPENCLAW_USER="${OPENCLAW_USER:-root}"
export OPENCLAW_PORT="${OPENCLAW_PORT:-22}"

cat <<EOF
==============================
task16 RL reproduction
MODEL=${VERL_MODEL}
DATA_DIR=${DATA_DIR}
TRAIN_FILE=${PINCHBENCH_TRAIN_FILE_OVERRIDE}
VAL_FILE=${PINCHBENCH_VAL_FILE_OVERRIDE}
REWARD_OVERRIDE=${PINCHBENCH_REWARD_MODULE_OVERRIDE}
NO_MASKED_WHITEN=${PINCHBENCH_NO_MASKED_WHITEN}
TOTAL_TRAINING_STEPS=${TOTAL_TRAINING_STEPS}
VAL_BEFORE_TRAIN=${VAL_BEFORE_TRAIN}
OPENCLAW=${OPENCLAW_USER}@${OPENCLAW_HOST:-<unset>}:${OPENCLAW_PORT}
LOG=${TRAIN_LOG_PATH}
DIAGNOSTICS=${PINCHBENCH_ROLLOUT_DIAGNOSTICS_PATH}
AGENT_LOOP_RUNTIME=${PINCHBENCH_AGENT_LOOP_RUNTIME}
OPENCLAW_MODEL=${PINCHBENCH_BENCHMARK_MODEL_ID} reasoning=${OPENCLAW_MODEL_REASONING}
OPENCLAW_SAMPLING=temp:${PINCHBENCH_MODEL_TEMPERATURE} top_p:${PINCHBENCH_MODEL_TOP_P} top_k:${PINCHBENCH_MODEL_TOP_K} maxTokens:${PINCHBENCH_OPENCLAW_MAX_TOKENS}
RL_TOOL_CALL_SUFFIX=${PINCHBENCH_RL_INJECT_TOOL_FORMAT_SUFFIX}
DRY_RUN=${DRY_RUN}
==============================
EOF

if [ "${PINCHBENCH_SKIP_TRAIN_INFER_PARITY:-0}" != "1" ]; then
  python3 "${REPO_ROOT}/scripts/check_train_infer_parity.py"
fi

if [ "${DRY_RUN}" = "1" ]; then
  bash "${REPO_ROOT}/rl/train/run_reinforce_lora.sh" --dry-run
else
  bash "${REPO_ROOT}/rl/train/run_reinforce_lora.sh" | tee "${TRAIN_LOG_PATH}"
fi
